package com.mitch.safevault.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// val seed = Color(0xFF0061A2)

internal val LightPrimary = Color(0xFF0061A3)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFD1E4FF)
internal val LightOnPrimaryContainer = Color(0xFF001D36)
internal val LightSecondary = Color(0xFF535F70)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFD6E4F7)
internal val LightOnSecondaryContainer = Color(0xFF0F1C2B)
internal val LightTertiary = Color(0xFF6B5778)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFF2DAFF)
internal val LightOnTertiaryContainer = Color(0xFF251432)
internal val LightError = Color(0xFFBA1A1A)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightOnErrorContainer = Color(0xFF410002)
internal val LightBackground = Color(0xFFFDFCFF)
internal val LightOnBackground = Color(0xFF1A1C1E)
internal val LightSurface = Color(0xFFFDFCFF)
internal val LightOnSurface = Color(0xFF1A1C1E)
internal val LightSurfaceVariant = Color(0xFFDFE2EB)
internal val LightOnSurfaceVariant = Color(0xFF42474E)
internal val LightOutline = Color(0xFF73777F)
internal val LightInverseOnSurface = Color(0xFFF1F0F4)
internal val LightInverseSurface = Color(0xFF2F3033)
internal val LightInversePrimary = Color(0xFF9ECAFF)
internal val LightSurfaceTint = Color(0xFF0061A3)
internal val LightOutlineVariant = Color(0xFFC3C7CF)
internal val LightScrim = Color(0xFF000000)

internal val DarkPrimary = Color(0xFF9ECAFF)
internal val DarkOnPrimary = Color(0xFF003258)
internal val DarkPrimaryContainer = Color(0xFF00497C)
internal val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
internal val DarkSecondary = Color(0xFFBAC8DB)
internal val DarkOnSecondary = Color(0xFF253140)
internal val DarkSecondaryContainer = Color(0xFF3B4858)
internal val DarkOnSecondaryContainer = Color(0xFFD6E4F7)
internal val DarkTertiary = Color(0xFFD6BEE5)
internal val DarkOnTertiary = Color(0xFF3B2948)
internal val DarkTertiaryContainer = Color(0xFF523F5F)
internal val DarkOnTertiaryContainer = Color(0xFFF2DAFF)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnError = Color(0xFF690005)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkBackground = Color(0xFF1A1C1E)
internal val DarkOnBackground = Color(0xFFE2E2E6)
internal val DarkSurface = Color(0xFF1A1C1E)
internal val DarkOnSurface = Color(0xFFE2E2E6)
internal val DarkSurfaceVariant = Color(0xFF42474E)
internal val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
internal val DarkOutline = Color(0xFF8D9199)
internal val DarkInverseOnSurface = Color(0xFF1A1C1E)
internal val DarkInverseSurface = Color(0xFFE2E2E6)
internal val DarkInversePrimary = Color(0xFF0061A3)
internal val DarkSurfaceTint = Color(0xFF9ECAFF)
internal val DarkOutlineVariant = Color(0xFF42474E)
internal val DarkScrim = Color(0xFF000000)
